#! /bin/sh
ORIGINAL_DIR=$(pwd)
cd $(dirname $0)

pgrep -x sxhkd > /dev/null || sxhkd -c sxhkdrc . &

bspc monitor eDP-1 -d I II III
bspc monitor HDMI-1 -d IV V VI

bspc config border_width        2 
bspc config window_gap          20

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

feh --no-fehbg --bg-fill wallpapers/wallpaper7.jpg
#picom --config configs/picom.conf &
polybar -c configs/polybar.ini &
#flatpak run io.github.jeffshee.Hidamari &
#ibus-daemon --xim --replace & disown
#ibus start & disown > /home/kachi/Videos/hehe

xsetroot -cursor_name left_ptr

cd ~
#cd $ORIGINAL_DIR
#echo $ORIGINAL_DIR
